/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package my.kitchenterminalui;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import javax.swing.SwingUtilities;

/**
 *
 * @author Kiana M. Yeo
 * @date April 18, 2026
 */
public class KitchenTerminalUI extends javax.swing.JFrame {
    
    private static final String FILE_PATH = "C:\\Kitchen Terminal\\Orders.txt";
    private static final int POLL_INTERVAL = 2000; // milliseconds
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(KitchenTerminalUI.class.getName());

    /**
     * Creates new form KitchenTerminalUI
     */
    public KitchenTerminalUI() {
        initComponents();
        startOrderMonitor();
    }

    private void startOrderMonitor() {
        Thread monitorThread = new Thread(this::monitorOrders);
        monitorThread.setDaemon(true);
        monitorThread.start();
    }

    private void monitorOrders() {
        Path path = Paths.get(FILE_PATH);
        try {
            if (!Files.exists(path)) {
                updateTextArea("Orders file not found.");
                return;
            }
            long lastModifiedTime
                    = Files.getLastModifiedTime(path).toMillis();
            while (true) {
                long currentModifiedTime
                        = Files.getLastModifiedTime(path).toMillis();
                if (currentModifiedTime > lastModifiedTime) {
                    displayOrders(path);
                    lastModifiedTime = currentModifiedTime;
                }
                Thread.sleep(POLL_INTERVAL);
            }
        } catch (IOException | InterruptedException e) {
            updateTextArea("Error: " + e.getMessage());
        }
    }

    private void displayOrders(Path path) {
    try {
        List<String> orders = Files.readAllLines(path);
        StringBuilder sb = new StringBuilder();

        sb.append("                      KITCHEN ORDERS\n\n");

        if (orders.isEmpty()) {
            sb.append("              No orders found.\n");
        } else {
            for (String order : orders) {

                if (order.startsWith("ORDER #")) {

                    // Space before each new order
                    if (sb.length() > "              KITCHEN ORDERS\n\n".length()) {
                        sb.append("\n");
                    }

                    sb.append("========================================\n");
                    sb.append(order).append("\n");

                } else if (order.startsWith("DATE:")) {

                    sb.append(order).append("\n");

                } else if (order.startsWith("TIME:")) {

                    sb.append(order).append("\n");
                    sb.append("----------------------------------------\n");

                } else if (order.startsWith("=")) {

                    // Ignore separator stored in Orders.txt

                } else if (!order.trim().isEmpty()) {

                    sb.append("  • ").append(order).append("\n");
                }
            }
        }

        sb.append("\n========================================");

        updateTextArea(sb.toString());

    } catch (IOException e) {
        updateTextArea("Error reading orders: " + e.getMessage());
    }
}

    /**
     * Safely update JTextArea (VERY IMPORTANT for Swing)
     */
    private void updateTextArea(String text) {
        SwingUtilities.invokeLater(() -> {
            jTextArea1.setText(text);
        });
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new KitchenTerminalUI().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
